language: node_js
dist: trusty

node_js:
  - "10"

addons:
  sonarcloud:
    organization: "gameindus"

install:
- npm install

script:
- npm run build
- npm run testWithCoverage
- npm run tslint
- sonar-scanner

cache:
  directories:
  - node_modules
  - node_cache
  - $HOME/.npm
  - $HOME/.sonar/cache
